summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos13.0-x86_64/releases/download/2023.06.18/pkg-config-0.29.2-macos13.0-x86_64.tar.xz
bin-sha: 595d2151c570616fc0fe7161d67a044dcd3d7dc8085e7b4636c0ec677c7439d3
