summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-13.0-x86_64/releases/download/2024.06.08/pkg-config-0.29.2-macos-13.0-x86_64.tar.xz
bin-sha: 72b701df438b746d0f650d4bed28e1ecd4008651af9ffb49162e90f033670d78
