summary: Keyboard configuration database for the X Window System
webpage: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
version: 2.37
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-13.0-x86_64/releases/download/2024.06.08/xkeyboard-config-2.37-macos-13.0-x86_64.tar.xz
bin-sha: 4ee11771669a0daec7af8c31474793a48013dd7b8cb89a6a5df8dca40881166c
